In [12]:
# Converting linear equations to matrix form

import re
import numpy as np

def parse_equation(equation, variables):
    # Initialize coefficients for each variable to 0
    coeffs = {var: 0 for var in variables}
    
    # Extract terms with their signs and coefficients
    terms = re.findall(r'[+-]?\s*\d*\s*[a-zA-Z]\d*', equation)
    
    for term in terms:
        # Extract the variable and coefficient in each term
        var = re.findall(r'[a-zA-Z]\d*', term)[0]
        coeff = re.findall(r'[+-]?\s*\d+', term)
        
        # Handle cases with implicit coefficients (e.g., +x1 => +1x1)
        if coeff:
            coeff = int(coeff[0].replace(" ", ""))
        else:
            coeff = 1 if term[0] not in '-+' else int(term[0] + '1')
        
        # Assign the coefficient to the corresponding variable
        coeffs[var] = coeff
    
    # Extract the constant on the right-hand side of the equation
    constant = re.findall(r'(?<=\=)\s*[+-]?\d+', equation)
    constant = int(constant[0]) if constant else 0
    
    # Return the list of coefficients and the constant
    return [coeffs[var] for var in variables], constant

def extract_variables(equations):
    # Extract variables in the format 'x', 'y', 'z', 'x1', 'x2', etc.
    variables = set(re.findall(r'[a-zA-Z]\d*', ' '.join(equations)))
    return sorted(variables, key=lambda x: (re.sub(r'\d+', '', x), int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0))

def create_matrix_form(equations):
    variables = extract_variables(equations)
    
    A = []
    b = []
    
    for equation in equations:
        coeffs, constant = parse_equation(equation, variables)
        A.append(coeffs)
        b.append(constant)
    
    return np.array(A), np.array(b), variables

def print_matrix_form(A, b, variables):
    # Print matrix A
    print("Matrix A:")
    print(np.array_str(A, precision=2, suppress_small=True))

    # Print vector x (variables)
    print("\nVector x (variables):")
    print(f"[{', '.join(variables)}]")

    # Print vector b
    print("\nVector b:")
    print(np.array_str(b, precision=2, suppress_small=True))

def main():
    equations = [
        # Uncomment either of these two blocks to test different cases

        # Case 1: Variables without subscripts
        # "4y + 2z = 1",
        # "2x + 3y + 5z = 0",
        # "3x + y + z = 11"
        
        # Case 2: Variables with subscripts
        "2x1 + x2 + 2x3 + x4 = 6",
        "6x1 - 6x2 + 6x3 + 12x4 = 36",
        "4x1 + 3x2 + 3x3 - 3x4 = -1",
        "2x1 + 2x2 - x3 + x4 = 10"
    ]
    
    A, b, variables = create_matrix_form(equations)
    print_matrix_form(A, b, variables)

if __name__ == "__main__":
    main()


Matrix A:
[[ 2  2  2  4]
 [ 6 -6  6 12]
 [ 4  3  3 -3]
 [ 2  2  3  4]]

Vector x (variables):
[x1, x2, x3, x4]

Vector b:
[ 6 36 -1 10]
