In [32]:
import numpy as np
import sympy as sym

sym.init_printing(use_unicode=True)

x, y, z, λ = sym.symbols('x y z λ')

In [37]:
# sum of all the weights of the edges connected to the node
D = np.matrix([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 0]])

# all the weights of the edges
W = np.matrix([[0, 1, 0],
               [1, 0, 0],
               [0, 0, 0]])

# identity matrix
I2 = np.matrix([[1, 0],
                [0, 1]])

# identity matrix
I3 = np.matrix([[1, 0, 0],
                [0, 1, 0],
                [0, 0, 1]])

c = 2

L = D - W
print(L)

[[ 1 -1  0]
 [-1  1  0]
 [ 0  0  0]]


In [38]:
sym.Matrix(L - λ*I3)

⎡1 - λ   -1    0 ⎤
⎢                ⎥
⎢ -1    1 - λ  0 ⎥
⎢                ⎥
⎣  0      0    -λ⎦

In [13]:
sym.Matrix(L).eigenvects()

⎡⎛      ⎡⎡1⎤  ⎡0⎤⎤⎞  ⎛      ⎡⎡-1⎤⎤⎞⎤
⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟  ⎜      ⎢⎢  ⎥⎥⎟⎥
⎢⎜0, 2, ⎢⎢1⎥, ⎢0⎥⎥⎟, ⎜2, 1, ⎢⎢1 ⎥⎥⎟⎥
⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟  ⎜      ⎢⎢  ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦  ⎣1⎦⎦⎠  ⎝      ⎣⎣0 ⎦⎦⎠⎦

In [45]:
# take 2-norm of minimum c eigenvectors
v = np.array([1, 1, 0])
v = v / np.linalg.norm(v)
v 

array([0.70710678, 0.70710678, 0.        ])

In [46]:
v = np.array([0, 0, 1])
v = v / np.linalg.norm(v)
v 

array([0., 0., 1.])